const cdmData = [
  {
    Model: `CreditModel`,
    Name: `Creditor`,
    Comment: `Entity representing a creditor (person or organization) that lends money.`,
    Ent_fr_name: `Créancier`,
    Ent_fr_comment: `Entité représentant un créancier (personne ou organisation) qui prête de l'argent.`,
    Mapping: `CREDITOR`,
    Datasource: `LOAN_SYSTEM`,
    Stereotype: `BusinessEntity`,
    TTS: `CREDITOR_TTS`,
    STSP: `Standard`,
    Shareable_link: `http://example.com/search?query=Creditor`,
    Creation_date: `3/1/2026 09:15:22 AM`,
    Modification_date: `3/5/2026 11:42:10 AM`,
    Creator: `sysadmin`,
    Modifier: `data_owner`,
    Diagrams: [
      {
        name: `Creditor Overview`,
        comment: `Main diagram for creditor entities.`,
        posX: `-2270`,
        posY: `11886`
      }
    ],
    Relationships: [
      {
        name: `<1..n>: Creditor ==> Processing Criteria`,
        ChildEntity: `Processing Criteria`,
        ParentEntity: `Creditor`,
        childCardinality: `0,n`,
        parentCardinality: `0,1`,
        DiagramContainers: `3-Processing Criteria of the Creditor`
      },
      {
        name: `<1..n>: Creditor ==> Asset`,
        ChildEntity: `Asset`,
        ParentEntity: `Creditor`,
        childCardinality: `0,n`,
        parentCardinality: `0,1`,
        DiagramContainers: `Creditor Assets`
      }
    ],
    Identifier: `CREDITOR_ID`,
    List_parent: `*`,
    List_child: `*`,
    Attributes: [
      {
        Name: `CreditorID`,
        Datatype: `A15`,
        Description: `Unique identifier for the creditor.`,
        FrName: `ID_Créancier`,
        FrDescription: `Identifiant unique du créancier.`,
        Primary: `True`,
        Mandatory: `True`,
        Mapping: `CREDITOR_ID`,
        Screen: `creditor_main`,
        STSP: `Standard`,
        TTS: `CREDITOR_ID_TTS`,
        Domain: `DOMAIN_ID`,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `Name`,
        Datatype: `A50`,
        Description: `Full name of the creditor.`,
        FrName: `Nom`,
        FrDescription: `Nom complet du créancier.`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `CREDITOR_NAME`,
        Screen: `creditor_main`,
        STSP: `Standard`,
        TTS: `CREDITOR_NAME_TTS`,
        Domain: ``,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `RegistrationNumber`,
        Datatype: `A20`,
        Description: `Official registration number (e.g., SIREN).`,
        FrName: `Numéro d'immatriculation`,
        FrDescription: `Numéro d'enregistrement officiel (ex: SIREN).`,
        Primary: ``,
        Mandatory: ``,
        Mapping: `REG_NUMBER`,
        Screen: `creditor_details`,
        STSP: `Standard`,
        TTS: `REG_NUMBER_TTS`,
        Domain: ``,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `Country`,
        Datatype: `A3`,
        Description: `Country code (ISO 3166-1 alpha-3).`,
        FrName: `Pays`,
        FrDescription: `Code pays (ISO 3166-1 alpha-3).`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `COUNTRY`,
        Screen: `creditor_main`,
        STSP: `Standard`,
        TTS: `COUNTRY_TTS`,
        Domain: `DOMAIN_COUNTRY`,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      }
    ]
  },
  {
    Model: `CreditModel`,
    Name: `Processing Criteria`,
    Comment: `Criteria used to evaluate a creditor (e.g., risk score, limits).`,
    Ent_fr_name: `Critères de traitement`,
    Ent_fr_comment: `Critères utilisés pour évaluer un créancier (ex: score de risque, limites).`,
    Mapping: `PROC_CRITERIA`,
    Datasource: `RISK_ENGINE`,
    Stereotype: `BusinessRule`,
    TTS: `PROC_CRITERIA_TTS`,
    STSP: `Standard`,
    Shareable_link: `http://example.com/search?query=Processing+Criteria`,
    Creation_date: `3/2/2026 10:30:45 AM`,
    Modification_date: `3/6/2026 14:20:12 PM`,
    Creator: `risk_analyst`,
    Modifier: `risk_analyst`,
    Diagrams: [
      {
        name: `Creditor Overview`,
        comment: `Main diagram for creditor entities.`,
        posX: `-1850`,
        posY: `12350`
      }
    ],
    Relationships: [
      {
        name: `<1..n>: Processing Criteria ==> Creditor`,
        ChildEntity: `Creditor`,
        ParentEntity: `Processing Criteria`,
        childCardinality: `0,n`,
        parentCardinality: `0,1`,
        DiagramContainers: `3-Processing Criteria of the Creditor`
      }
    ],
    Identifier: `CRITERIA_ID`,
    List_parent: `*`,
    List_child: `*`,
    Attributes: [
      {
        Name: `CriteriaID`,
        Datatype: `A15`,
        Description: `Unique identifier for the criteria set.`,
        FrName: `ID_Critère`,
        FrDescription: `Identifiant unique de l'ensemble de critères.`,
        Primary: `True`,
        Mandatory: `True`,
        Mapping: `CRITERIA_ID`,
        Screen: `criteria_main`,
        STSP: `Standard`,
        TTS: `CRITERIA_ID_TTS`,
        Domain: `DOMAIN_ID`,
        Creation_date: `3/2/2026 10:30:45 AM`,
        Modification_date: `3/6/2026 14:20:12 PM`,
        Creator: `risk_analyst`,
        Modifier: `risk_analyst`
      },
      {
        Name: `RiskScore`,
        Datatype: `MN5,2`,
        Description: `Calculated risk score (0-100).`,
        FrName: `Score de risque`,
        FrDescription: `Score de risque calculé (0-100).`,
        Primary: ``,
        Mandatory: ``,
        Mapping: `RISK_SCORE`,
        Screen: `criteria_details`,
        STSP: `Standard`,
        TTS: `RISK_SCORE_TTS`,
        Domain: `DOMAIN_PERCENT`,
        Creation_date: `3/2/2026 10:30:45 AM`,
        Modification_date: `3/6/2026 14:20:12 PM`,
        Creator: `risk_analyst`,
        Modifier: `risk_analyst`
      },
      {
        Name: `CreditLimit`,
        Datatype: `MN13,2`,
        Description: `Maximum credit amount allowed.`,
        FrName: `Limite de crédit`,
        FrDescription: `Montant de crédit maximum autorisé.`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `CREDIT_LIMIT`,
        Screen: `criteria_main`,
        STSP: `Standard`,
        TTS: `CREDIT_LIMIT_TTS`,
        Domain: `DOMAIN_AMOUNT`,
        Creation_date: `3/2/2026 10:30:45 AM`,
        Modification_date: `3/6/2026 14:20:12 PM`,
        Creator: `risk_analyst`,
        Modifier: `risk_analyst`
      },
      {
        Name: `ValidFrom`,
        Datatype: `DATE`,
        Description: `Start date of criteria validity.`,
        FrName: `Valide du`,
        FrDescription: `Date de début de validité des critères.`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `VALID_FROM`,
        Screen: `criteria_main`,
        STSP: `Standard`,
        TTS: `VALID_FROM_TTS`,
        Domain: ``,
        Creation_date: `3/2/2026 10:30:45 AM`,
        Modification_date: `3/6/2026 14:20:12 PM`,
        Creator: `risk_analyst`,
        Modifier: `risk_analyst`
      },
      {
        Name: `ValidTo`,
        Datatype: `DATE`,
        Description: `End date of criteria validity (nullable).`,
        FrName: `Valide au`,
        FrDescription: `Date de fin de validité des critères (nullable).`,
        Primary: ``,
        Mandatory: ``,
        Mapping: `VALID_TO`,
        Screen: `criteria_main`,
        STSP: `Standard`,
        TTS: `VALID_TO_TTS`,
        Domain: ``,
        Creation_date: `3/2/2026 10:30:45 AM`,
        Modification_date: `3/6/2026 14:20:12 PM`,
        Creator: `risk_analyst`,
        Modifier: `risk_analyst`
      }
    ]
  },
  {
    Model: `CreditModel`,
    Name: `Asset`,
    Comment: `Assets owned by a creditor (e.g., properties, vehicles).`,
    Ent_fr_name: `Actif`,
    Ent_fr_comment: `Actifs détenus par un créancier (ex: biens immobiliers, véhicules).`,
    Mapping: `ASSET`,
    Datasource: `ASSET_MGMT`,
    Stereotype: `BusinessObject`,
    TTS: `ASSET_TTS`,
    STSP: `Standard`,
    Shareable_link: `http://example.com/search?query=Asset`,
    Creation_date: `3/3/2026 08:45:30 AM`,
    Modification_date: `3/7/2026 09:30:15 AM`,
    Creator: `asset_admin`,
    Modifier: `asset_admin`,
    Diagrams: [
      {
        name: `Creditor Assets`,
        comment: `Diagram showing assets linked to creditors.`,
        posX: `-1500`,
        posY: `13000`
      }
    ],
    Relationships: [
      {
        name: `<1..n>: Asset ==> Creditor`,
        ChildEntity: `Creditor`,
        ParentEntity: `Asset`,
        childCardinality: `0,n`,
        parentCardinality: `0,1`,
        DiagramContainers: `Creditor Assets`
      }
    ],
    Identifier: `ASSET_ID`,
    List_parent: `*`,
    List_child: `*`,
    Attributes: [
      {
        Name: `AssetID`,
        Datatype: `A15`,
        Description: `Unique identifier for the asset.`,
        FrName: `ID_Actif`,
        FrDescription: `Identifiant unique de l'actif.`,
        Primary: `True`,
        Mandatory: `True`,
        Mapping: `ASSET_ID`,
        Screen: `asset_main`,
        STSP: `Standard`,
        TTS: `ASSET_ID_TTS`,
        Domain: `DOMAIN_ID`,
        Creation_date: `3/3/2026 08:45:30 AM`,
        Modification_date: `3/7/2026 09:30:15 AM`,
        Creator: `asset_admin`,
        Modifier: `asset_admin`
      },
      {
        Name: `Type`,
        Datatype: `A30`,
        Description: `Type of asset (e.g., RealEstate, Vehicle, Cash).`,
        FrName: `Type`,
        FrDescription: `Type d'actif (ex: Immobilier, Véhicule, Trésorerie).`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `ASSET_TYPE`,
        Screen: `asset_main`,
        STSP: `Standard`,
        TTS: `ASSET_TYPE_TTS`,
        Domain: `DOMAIN_ASSET_TYPE`,
        Creation_date: `3/3/2026 08:45:30 AM`,
        Modification_date: `3/7/2026 09:30:15 AM`,
        Creator: `asset_admin`,
        Modifier: `asset_admin`
      },
      {
        Name: `Value`,
        Datatype: `MN13,2`,
        Description: `Monetary value of the asset.`,
        FrName: `Valeur`,
        FrDescription: `Valeur monétaire de l'actif.`,
        Primary: ``,
        Mandatory: `True`,
        Mapping: `ASSET_VALUE`,
        Screen: `asset_main`,
        STSP: `Standard`,
        TTS: `ASSET_VALUE_TTS`,
        Domain: `DOMAIN_AMOUNT`,
        Creation_date: `3/3/2026 08:45:30 AM`,
        Modification_date: `3/7/2026 09:30:15 AM`,
        Creator: `asset_admin`,
        Modifier: `asset_admin`
      },
      {
        Name: `Description`,
        Datatype: `A200`,
        Description: `Free-text description of the asset.`,
        FrName: `Description`,
        FrDescription: `Description libre de l'actif.`,
        Primary: ``,
        Mandatory: ``,
        Mapping: `ASSET_DESC`,
        Screen: `asset_details`,
        STSP: `Standard`,
        TTS: `ASSET_DESC_TTS`,
        Domain: ``,
        Creation_date: `3/3/2026 08:45:30 AM`,
        Modification_date: `3/7/2026 09:30:15 AM`,
        Creator: `asset_admin`,
        Modifier: `asset_admin`
      },
      {
        Name: `AcquisitionDate`,
        Datatype: `DATE`,
        Description: `Date when the asset was acquired.`,
        FrName: `Date d'acquisition`,
        FrDescription: `Date à laquelle l'actif a été acquis.`,
        Primary: ``,
        Mandatory: ``,
        Mapping: `ACQ_DATE`,
        Screen: `asset_main`,
        STSP: `Standard`,
        TTS: `ACQ_DATE_TTS`,
        Domain: ``,
        Creation_date: `3/3/2026 08:45:30 AM`,
        Modification_date: `3/7/2026 09:30:15 AM`,
        Creator: `asset_admin`,
        Modifier: `asset_admin`
      }
    ]
  }
];

window.cdmData = cdmData;