const pdmData = [
  {
    Model: `SalesModel`,
    Name: `T_CUSTOMER`,
    Code: `T_CUSTOMER`,
    Comment: `Customer master data – stores contact and account information.`,
    Stereotype: ``,
    Identifier: ``,
    Shareable_link: `http://example.com/search?query=T_CUSTOMER`,
    Creation_date: `3/1/2026 09:15:22 AM`,
    Modification_date: `3/5/2026 11:42:10 AM`,
    Creator: `sysadmin`,
    Modifier: `data_owner`,
    DCL: ``,
    Diagrams: [
      {
        name: `Sales Overview`,
        comment: `Main customer and order diagram.`,
        posX: `12500`,
        posY: `-2300`
      }
    ],
    Checks: [
      {
        name: `CK_CUSTOMER_STATUS`,
        code: `CK_CUSTOMER_STATUS`,
        ServerExpression: `STATUS IN ('ACTIVE','INACTIVE','SUSPENDED')`
      }
    ],
    References: [
      {
        name: `T_CUSTOMER.REFCUST=T_ORDER.REFCUST`,
        ChildTable: `T_ORDER`,
        ParentTable: `T_CUSTOMER`,
        ChildColumn: `REFCUST`,
        ParentColumn: `REFCUST`,
        Cardinality: `0..*`,
        MinimumCardinality: `0`,
        MaximumCardinality: `*`,
        Generated: `True`,
        Mandatory: `True`,
        DiagramContainers: `Sales Overview`
      }
    ],
    Columns: [
      {
        Name: `REFCUST`,
        Code: `REFCUST`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Unique customer identifier (generated from sequence SEQ_CUST).`,
        Mandatory: `True`,
        Primary: `True`,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: `SEQ_CUST`,
        Identifier: `REFCUST`,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `NAME`,
        Code: `NAME`,
        Datatype: `VARCHAR2(100)`,
        Description: ``,
        Comment: `Customer full name or company name.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `EMAIL`,
        Code: `EMAIL`,
        Datatype: `VARCHAR2(150)`,
        Description: ``,
        Comment: `Primary email address.`,
        Mandatory: ``,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: `AK_CUSTOMER_EMAIL`,
        AK_Constraint: `AK_CUSTOMER_EMAIL`,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      },
      {
        Name: `STATUS`,
        Code: `STATUS`,
        Datatype: `VARCHAR2(20)`,
        Description: ``,
        Comment: `Account status (ACTIVE, INACTIVE, SUSPENDED).`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 09:15:22 AM`,
        Modification_date: `3/5/2026 11:42:10 AM`,
        Creator: `sysadmin`,
        Modifier: `data_owner`
      }
    ]
  },
  {
    Model: `SalesModel`,
    Name: `T_ORDER`,
    Code: `T_ORDER`,
    Comment: `Customer orders – header information.`,
    Stereotype: ``,
    Identifier: ``,
    Shareable_link: `http://example.com/search?query=T_ORDER`,
    Creation_date: `3/2/2026 14:30:05 PM`,
    Modification_date: `3/6/2026 08:20:33 AM`,
    Creator: `sysadmin`,
    Modifier: `order_clerk`,
    DCL: ``,
    Diagrams: [
      {
        name: `Sales Overview`,
        comment: `Main customer and order diagram.`,
        posX: `15800`,
        posY: `-2100`
      }
    ],
    Checks: [
      {
        name: `CK_ORDER_AMOUNT`,
        code: `CK_ORDER_AMOUNT`,
        ServerExpression: `TOTAL_AMOUNT >= 0`
      }
    ],
    References: [
      {
        name: `T_ORDER.REFCUST=T_CUSTOMER.REFCUST`,
        ChildTable: `T_ORDER`,
        ParentTable: `T_CUSTOMER`,
        ChildColumn: `REFCUST`,
        ParentColumn: `REFCUST`,
        Cardinality: `*..1`,
        MinimumCardinality: `1`,
        MaximumCardinality: `1`,
        Generated: `True`,
        Mandatory: `True`,
        DiagramContainers: `Sales Overview`
      },
      {
        name: `T_ORDER.REFORD=T_ORDER_LINE.REFORD`,
        ChildTable: `T_ORDER_LINE`,
        ParentTable: `T_ORDER`,
        ChildColumn: `REFORD`,
        ParentColumn: `REFORD`,
        Cardinality: `0..*`,
        MinimumCardinality: `0`,
        MaximumCardinality: `*`,
        Generated: `True`,
        Mandatory: `True`,
        DiagramContainers: `Sales Overview`
      }
    ],
    Columns: [
      {
        Name: `REFORD`,
        Code: `REFORD`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Order identifier (sequence SEQ_ORD).`,
        Mandatory: `True`,
        Primary: `True`,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: `SEQ_ORD`,
        Identifier: `REFORD`,
        Creation_date: `3/2/2026 14:30:05 PM`,
        Modification_date: `3/6/2026 08:20:33 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `REFCUST`,
        Code: `REFCUST`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Foreign key to T_CUSTOMER.`,
        Mandatory: `True`,
        Primary: ``,
        FK: `True`,
        FK_Reference: `T_CUSTOMER.REFCUST=T_ORDER.REFCUST`,
        FK_Constraint: `FK_ORDER_CUSTOMER`,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_ORDER_CUST`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/2/2026 14:30:05 PM`,
        Modification_date: `3/6/2026 08:20:33 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `ORDER_DATE`,
        Code: `ORDER_DATE`,
        Datatype: `DATE`,
        Description: ``,
        Comment: `Date when order was placed.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_ORDER_DATE`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/2/2026 14:30:05 PM`,
        Modification_date: `3/6/2026 08:20:33 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `TOTAL_AMOUNT`,
        Code: `TOTAL_AMOUNT`,
        Datatype: `NUMBER(12,2)`,
        Description: ``,
        Comment: `Sum of all order lines.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/2/2026 14:30:05 PM`,
        Modification_date: `3/6/2026 08:20:33 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `STATUS`,
        Code: `STATUS`,
        Datatype: `VARCHAR2(20)`,
        Description: ``,
        Comment: `Order status (NEW, PROCESSING, SHIPPED, CANCELLED).`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_ORDER_STATUS`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/2/2026 14:30:05 PM`,
        Modification_date: `3/6/2026 08:20:33 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      }
    ]
  },
  {
    Model: `SalesModel`,
    Name: `T_ORDER_LINE`,
    Code: `T_ORDER_LINE`,
    Comment: `Order line items – products and quantities.`,
    Stereotype: ``,
    Identifier: ``,
    Shareable_link: `http://example.com/search?query=T_ORDER_LINE`,
    Creation_date: `3/3/2026 10:05:47 AM`,
    Modification_date: `3/7/2026 09:12:18 AM`,
    Creator: `sysadmin`,
    Modifier: `order_clerk`,
    DCL: ``,
    Diagrams: [
      {
        name: `Sales Overview`,
        comment: `Main customer and order diagram.`,
        posX: `18200`,
        posY: `-1900`
      }
    ],
    Checks: [
      {
        name: `CK_LINE_QUANTITY`,
        code: `CK_LINE_QUANTITY`,
        ServerExpression: `QUANTITY > 0`
      }
    ],
    References: [
      {
        name: `T_ORDER_LINE.REFORD=T_ORDER.REFORD`,
        ChildTable: `T_ORDER_LINE`,
        ParentTable: `T_ORDER`,
        ChildColumn: `REFORD`,
        ParentColumn: `REFORD`,
        Cardinality: `*..1`,
        MinimumCardinality: `1`,
        MaximumCardinality: `1`,
        Generated: `True`,
        Mandatory: `True`,
        DiagramContainers: `Sales Overview`
      },
      {
        name: `T_ORDER_LINE.REFPRD=T_PRODUCT.REFPRD`,
        ChildTable: `T_ORDER_LINE`,
        ParentTable: `T_PRODUCT`,
        ChildColumn: `REFPRD`,
        ParentColumn: `REFPRD`,
        Cardinality: `*..1`,
        MinimumCardinality: `1`,
        MaximumCardinality: `1`,
        Generated: `True`,
        Mandatory: `True`,
        DiagramContainers: `Sales Overview`
      }
    ],
    Columns: [
      {
        Name: `REFLINE`,
        Code: `REFLINE`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Order line identifier (sequence SEQ_ORD_LINE).`,
        Mandatory: `True`,
        Primary: `True`,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: `SEQ_ORD_LINE`,
        Identifier: `REFLINE`,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `REFORD`,
        Code: `REFORD`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Foreign key to T_ORDER.`,
        Mandatory: `True`,
        Primary: ``,
        FK: `True`,
        FK_Reference: `T_ORDER.REFORD=T_ORDER_LINE.REFORD`,
        FK_Constraint: `FK_LINE_ORDER`,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_LINE_ORD`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `REFPRD`,
        Code: `REFPRD`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Foreign key to T_PRODUCT.`,
        Mandatory: `True`,
        Primary: ``,
        FK: `True`,
        FK_Reference: `T_PRODUCT.REFPRD=T_ORDER_LINE.REFPRD`,
        FK_Constraint: `FK_LINE_PRODUCT`,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_LINE_PRD`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `QUANTITY`,
        Code: `QUANTITY`,
        Datatype: `NUMBER(5)`,
        Description: ``,
        Comment: `Number of units ordered.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `UNIT_PRICE`,
        Code: `UNIT_PRICE`,
        Datatype: `NUMBER(10,2)`,
        Description: ``,
        Comment: `Price per unit at time of order.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      },
      {
        Name: `LINE_TOTAL`,
        Code: `LINE_TOTAL`,
        Datatype: `NUMBER(12,2)`,
        Description: ``,
        Comment: `Computed as QUANTITY * UNIT_PRICE.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/3/2026 10:05:47 AM`,
        Modification_date: `3/7/2026 09:12:18 AM`,
        Creator: `sysadmin`,
        Modifier: `order_clerk`
      }
    ]
  },
  {
    Model: `SalesModel`,
    Name: `T_PRODUCT`,
    Code: `T_PRODUCT`,
    Comment: `Product catalog – items that can be ordered.`,
    Stereotype: ``,
    Identifier: ``,
    Shareable_link: `http://example.com/search?query=T_PRODUCT`,
    Creation_date: `3/1/2026 11:00:13 AM`,
    Modification_date: `3/4/2026 16:45:22 PM`,
    Creator: `sysadmin`,
    Modifier: `product_manager`,
    DCL: ``,
    Diagrams: [
      {
        name: `Sales Overview`,
        comment: `Main customer and order diagram.`,
        posX: `14200`,
        posY: `-2600`
      }
    ],
    Checks: [
      {
        name: `CK_PRODUCT_PRICE`,
        code: `CK_PRODUCT_PRICE`,
        ServerExpression: `LIST_PRICE >= 0`
      }
    ],
    References: [],
    Columns: [
      {
        Name: `REFPRD`,
        Code: `REFPRD`,
        Datatype: `NUMBER(10)`,
        Description: ``,
        Comment: `Product identifier (sequence SEQ_PRD).`,
        Mandatory: `True`,
        Primary: `True`,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: `SEQ_PRD`,
        Identifier: `REFPRD`,
        Creation_date: `3/1/2026 11:00:13 AM`,
        Modification_date: `3/4/2026 16:45:22 PM`,
        Creator: `sysadmin`,
        Modifier: `product_manager`
      },
      {
        Name: `PRODUCT_NAME`,
        Code: `PRODUCT_NAME`,
        Datatype: `VARCHAR2(200)`,
        Description: ``,
        Comment: `Display name of the product.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: `AK_PRODUCT_NAME`,
        AK_Constraint: `AK_PRODUCT_NAME`,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 11:00:13 AM`,
        Modification_date: `3/4/2026 16:45:22 PM`,
        Creator: `sysadmin`,
        Modifier: `product_manager`
      },
      {
        Name: `DESCRIPTION`,
        Code: `DESCRIPTION`,
        Datatype: `VARCHAR2(500)`,
        Description: ``,
        Comment: `Detailed product description.`,
        Mandatory: ``,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 11:00:13 AM`,
        Modification_date: `3/4/2026 16:45:22 PM`,
        Creator: `sysadmin`,
        Modifier: `product_manager`
      },
      {
        Name: `LIST_PRICE`,
        Code: `LIST_PRICE`,
        Datatype: `NUMBER(10,2)`,
        Description: ``,
        Comment: `Standard selling price.`,
        Mandatory: `True`,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: ``,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 11:00:13 AM`,
        Modification_date: `3/4/2026 16:45:22 PM`,
        Creator: `sysadmin`,
        Modifier: `product_manager`
      },
      {
        Name: `CATEGORY`,
        Code: `CATEGORY`,
        Datatype: `VARCHAR2(50)`,
        Description: ``,
        Comment: `Product category (e.g., ELECTRONICS, CLOTHING).`,
        Mandatory: ``,
        Primary: ``,
        FK: ``,
        FK_Reference: ``,
        FK_Constraint: ``,
        AK: ``,
        AK_Constraint: ``,
        Index: `IDX_PRD_CAT`,
        Sequence: ``,
        Identifier: ``,
        Creation_date: `3/1/2026 11:00:13 AM`,
        Modification_date: `3/4/2026 16:45:22 PM`,
        Creator: `sysadmin`,
        Modifier: `product_manager`
      }
    ]
  }
];

window.pdmData = pdmData;